/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamiento;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anthony
 */
public class JFrameRegistro extends javax.swing.JFrame {

    /**
     * Creates new form JFrameRegistro
     */
    public JFrameRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        visor = new javax.swing.JTable();
        txtid_registro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        datellegada = new com.toedter.calendar.JDateChooser();
        datesalida = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_vehiculo = new javax.swing.JTextField();
        txt_espacio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Registro");

        jLabel2.setText("Hora de llegada");

        jLabel3.setText("Hora de Salida");

        btnNuevo.setText("nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        visor.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        visor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(visor);

        txtid_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid_registroActionPerformed(evt);
            }
        });

        jLabel4.setText("Id_registro");

        btnguardar.setText("guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        datellegada.setDateFormatString("yyyy-MM-dd HH:mm:ss");

        datesalida.setDateFormatString("yyyy-MM-dd HH:mm:ss");

        jLabel5.setText("Id_vehiculo");

        jLabel6.setText("Id_Espacio");

        txt_vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(8, 8, 8)
                                                                .addComponent(jLabel6))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(jLabel4))
                                                                .addGap(15, 15, 15)))
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(31, 31, 31)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(datellegada,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        144, Short.MAX_VALUE)
                                                                                .addComponent(datesalida,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addComponent(txt_espacio))
                                                                        .addComponent(txtid_registro,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                144,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txt_vehiculo,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                144,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(74, 74, 74)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(btnguardar)
                                                                        .addComponent(btnNuevo)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(99, 99, 99)
                                                                .addComponent(jLabel1)))))
                                .addContainerGap(23, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnNuevo)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtid_registro,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txt_vehiculo,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5))))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnguardar)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel2))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(txt_espacio,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel6))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(datellegada,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(datesalida, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(42, 42, 42)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtid_registroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtid_registroActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtid_registroActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this.nuevo();
    }// GEN-LAST:event_btnNuevoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnguardarActionPerformed
        try {
            // TODO add your handling code here:
            this.enviar();
        } catch (Exception ex) {
            Logger.getLogger(JFrameRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_btnguardarActionPerformed

    private void visorMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_visorMouseClicked
        this.MouseClick();
    }// GEN-LAST:event_visorMouseClicked

    private void txt_vehiculoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_vehiculoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txt_vehiculoActionPerformed

    public boolean verificarespacioregistrado(int id_espacio) throws SQLException, Exception {
        espacio usuarioBD = new espacio();
        usuarioBD.setId_espacio(id_espacio);
        ResultSet rs = usuarioBD.consultarid_espacio();

        // Check if there are any rows in the ResultSet
        return rs.next();
    }

    public boolean verificarhehiculoregistrado(int id_vehiculo) throws SQLException, Exception {
        Vehiculo usuarioBD = new Vehiculo();
        usuarioBD.setId_vehiculo(id_vehiculo);
        ResultSet rs = usuarioBD.consultarid_vehiculo();

        // Check if there are any rows in the ResultSet
        return rs.next();
    }

    private void validar(int id_espacio, int Id_vehiculo) {
        try {
            boolean espacioRegistrado = verificarespacioregistrado(id_espacio);
            boolean vehiculoRegistrado = verificarhehiculoregistrado(Id_vehiculo);

            if (espacioRegistrado && vehiculoRegistrado) {

                JFrameVehiculo jfVehiculo = new JFrameVehiculo();
                jfVehiculo.setVisible(true);

                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                frame.dispose();
            } else if (!espacioRegistrado) {

            } else if (!vehiculoRegistrado) {

            }

        } catch (Exception e) {
            e.printStackTrace();
            // Handle the exception appropriately
        }
    }

    private void enviar() throws Exception {
        try {
            registro cb = new registro();

            int vehiculo = Integer.parseInt(txt_vehiculo.getText());
            int espacio = Integer.parseInt(txt_espacio.getText());

            if (verificarhehiculoregistrado(vehiculo) && verificarespacioregistrado(espacio)) {
                cb.setId_registro(Integer.parseInt(txtid_registro.getText()));
                cb.setId_vehiculo(Integer.parseInt(txt_vehiculo.getText()));
                cb.setId_espacio(Integer.parseInt(txt_espacio.getText()));
                cb.setFecha_hora_entrada(LocalDateTime.now());
                cb.setFecha_hora_salida(LocalDateTime.now());
                cb.insertar_Registro();
                JOptionPane.showMessageDialog(null, "La información ha sido guardada con éxito");
            } else {
                JOptionPane.showMessageDialog(null, "El ID_USUARIO no existe en la tabla usuario");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
        }
    }

    private void nuevo() {
        try {
            registro cb = new registro();
            txtid_registro.setText("" + cb.incremento_Registro());
            datellegada.setDate(null);
            datesalida.setDate(null);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error..." + e.toString());
        }
    }

    private void mostrar(javax.swing.JTable JT, String sql) throws Exception {
        try {
            registro cb = new registro();
            ResultSet rs = cb.consultaTabla(sql);
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantColumnas = rsMd.getColumnCount();

            DefaultTableModel modelo = new DefaultTableModel();
            JT.setModel(modelo);

            // Agregar las columnas al modelo de la tabla
            for (int i = 1; i <= cantColumnas; i++) {
                modelo.addColumn(rsMd.getColumnLabel(i));
            }

            // Agregar las filas al modelo de la tabla
            while (rs.next()) {
                Object[] columna = new Object[cantColumnas];
                for (int i = 0; i < cantColumnas; i++) {
                    columna[i] = rs.getObject(i + 1);
                }
                modelo.addRow(columna);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
        }
    }

    private void MouseClick() {
        int fila = visor.getSelectedRow();
        txtid_registro.setText(visor.getModel().getValueAt(fila, 0).toString());
        datellegada.setDate((Date) visor.getModel().getValueAt(fila, 1));
        datesalida.setDate((Date) visor.getModel().getValueAt(fila, 2));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnguardar;
    private com.toedter.calendar.JDateChooser datellegada;
    private com.toedter.calendar.JDateChooser datesalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_espacio;
    private javax.swing.JTextField txt_vehiculo;
    private javax.swing.JTextField txtid_registro;
    private javax.swing.JTable visor;
    // End of variables declaration//GEN-END:variables
}
